version: "3.8"
services:
  api:
    # image: dontelmo/kudos_api/
    networks:
      - kudos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
      - DATABASE_INIT_FILE=db.sql # TODO: remove
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8000
    depends_on:
      - db

  db:
    networks:
      - kudos
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
#     volumes:
#       - pgdata:/var/lib/postgresql/data

  db-test:
    networks:
      - kudos
    image: postgres:latest
    ports:
      - "${TEST_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:-database_test}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-password}
    volumes:
      - ./db.sql:/db.sql

# volumes:
#   pgdata:

networks:
  kudos:
    driver: bridge
