name: Stage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features

      - name: Build code
        run: |
          cargo build --verbose

      - name: Test code
        run: |
          make test

      - name: Integration tests
        run: |
          make test-db
        env:
          DATABASE_URL: ${{ secrets.TESTS_DATABASE_URL }}

      - name: Build docker image
        run: |
          docker build -t ${{ vars.DOCKER_REGISTRY }}:${{ github.sha }} -f Dockerfile .
